name: Grammar check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run yaspeller
        run: |
          sudo npm install yaspeller -g
          yaspeller ./skill/texts.py --ignore-latin